import type { CatalogComponent, ComponentKind } from './types'

export const componentCatalog: CatalogComponent[] = [
  {
    kind: 'audioInput',
    category: 'sources',
    name: 'Audio input',
    shortName: 'AUDIO',
    description: 'External or generated audio source',
    modelStage: 'electrical',
    color: '#f2bf5e',
    size: { width: 92, height: 62 },
    ports: [{ id: 'out', label: 'OUT', side: 'right', offset: 31, signal: 'audio', direction: 'output', pinNumber: '1' }],
    defaultParameters: { frequency: 220, amplitude: 5 },
    kicadLibraryId: 'Simulation_SPICE:VSIN',
  },
  {
    kind: 'cvInput',
    category: 'sources',
    name: 'Constant CV',
    shortName: 'CV',
    description: 'Live bipolar constant voltage for offsets and pitch CV',
    modelStage: 'behavioral',
    color: '#9ad6c5',
    size: { width: 92, height: 62 },
    ports: [{ id: 'out', label: 'CV', side: 'right', offset: 31, signal: 'cv', direction: 'output', pinNumber: '1' }],
    defaultParameters: { voltage: 0 },
    kicadLibraryId: 'Connector_Generic:Conn_01x01',
  },
  {
    kind: 'gateInput',
    category: 'sources',
    name: 'Gate source',
    shortName: 'GATE',
    description: 'Live high/low gate with adjustable voltage',
    modelStage: 'electrical',
    color: '#d7a3e8',
    size: { width: 92, height: 62 },
    ports: [{ id: 'out', label: 'GATE', side: 'right', offset: 31, signal: 'gate', direction: 'output', pinNumber: '1' }],
    defaultParameters: { voltage: 5, state: 1 },
    kicadLibraryId: 'Connector_Generic:Conn_01x01',
  },
  {
    kind: 'triggerSource',
    category: 'sources',
    name: 'Trigger generator',
    shortName: 'TRIG',
    description: 'Adjustable repeating trigger pulse source',
    modelStage: 'behavioral',
    color: '#d7a3e8',
    size: { width: 118, height: 84 },
    ports: [
      { id: 'trigger', label: 'TRIG', side: 'right', offset: 42, signal: 'gate', direction: 'output', pinNumber: '1' },
    ],
    defaultParameters: { rate: 2, pulseWidthMs: 10, voltage: 5 },
    kicadLibraryId: 'Saigen_Blocks:Trigger',
  },
  {
    kind: 'functionGenerator',
    category: 'sources',
    name: 'Function generator',
    shortName: 'FUNC',
    description: 'Frequency source with sine, triangle, saw, and pulse outputs',
    modelStage: 'behavioral',
    color: '#f2bf5e',
    size: { width: 148, height: 132 },
    ports: [
      { id: 'sync', label: 'SYNC', side: 'left', offset: 66, signal: 'gate', direction: 'input', pinNumber: '1' },
      { id: 'sine', label: 'SINE', side: 'right', offset: 24, signal: 'audio', direction: 'output', pinNumber: '2' },
      { id: 'triangle', label: 'TRI', side: 'right', offset: 52, signal: 'audio', direction: 'output', pinNumber: '3' },
      { id: 'saw', label: 'SAW', side: 'right', offset: 80, signal: 'audio', direction: 'output', pinNumber: '4' },
      { id: 'pulse', label: 'PULSE', side: 'right', offset: 108, signal: 'audio', direction: 'output', pinNumber: '5' },
    ],
    defaultParameters: { frequency: 220, amplitude: 5, offset: 0, dutyCycle: 0.5 },
    kicadLibraryId: 'Saigen_Blocks:FunctionGenerator',
  },
  {
    kind: 'lfo',
    category: 'sources',
    name: 'Low-frequency oscillator',
    shortName: 'LFO',
    description: 'Sine, triangle, and square modulation source',
    modelStage: 'behavioral',
    color: '#68c7b2',
    size: { width: 132, height: 112 },
    ports: [
      { id: 'rate', label: 'RATE', side: 'left', offset: 31, signal: 'cv', direction: 'input', pinNumber: '1' },
      { id: 'reset', label: 'RESET', side: 'left', offset: 79, signal: 'gate', direction: 'input', pinNumber: '2' },
      { id: 'sine', label: 'SINE', side: 'right', offset: 25, signal: 'cv', direction: 'output', pinNumber: '3' },
      { id: 'triangle', label: 'TRI', side: 'right', offset: 56, signal: 'cv', direction: 'output', pinNumber: '4' },
      { id: 'square', label: 'SQR', side: 'right', offset: 87, signal: 'cv', direction: 'output', pinNumber: '5' },
    ],
    defaultParameters: { frequency: 1, amplitude: 5, offset: 0 },
    kicadLibraryId: 'Saigen_Blocks:LFO',
  },
  {
    kind: 'noiseSource',
    category: 'sources',
    name: 'Noise source',
    shortName: 'NOISE',
    description: 'White and pink analog noise generator',
    modelStage: 'behavioral',
    color: '#8daadd',
    size: { width: 118, height: 84 },
    ports: [
      { id: 'white', label: 'WHITE', side: 'right', offset: 27, signal: 'audio', direction: 'output', pinNumber: '1' },
      { id: 'pink', label: 'PINK', side: 'right', offset: 59, signal: 'audio', direction: 'output', pinNumber: '2' },
    ],
    defaultParameters: { amplitude: 5 },
    kicadLibraryId: 'Saigen_Blocks:Noise',
  },
  {
    kind: 'clock',
    category: 'sources',
    name: 'Clock generator',
    shortName: 'CLOCK',
    description: 'Tempo clock with reset and divided output',
    modelStage: 'behavioral',
    color: '#d7a3e8',
    size: { width: 118, height: 92 },
    ports: [
      { id: 'reset', label: 'RESET', side: 'left', offset: 46, signal: 'gate', direction: 'input', pinNumber: '1' },
      { id: 'clock', label: 'CLK', side: 'right', offset: 28, signal: 'gate', direction: 'output', pinNumber: '2' },
      { id: 'divide', label: '÷2', side: 'right', offset: 64, signal: 'gate', direction: 'output', pinNumber: '3' },
    ],
    defaultParameters: { bpm: 120, dutyCycle: 0.5 },
    kicadLibraryId: 'Saigen_Blocks:Clock',
  },
  {
    kind: 'resistor',
    category: 'passives',
    name: 'Resistor',
    shortName: 'R',
    description: 'Standard two-terminal resistor',
    modelStage: 'electrical',
    color: '#e5e1d8',
    size: { width: 112, height: 54 },
    ports: [
      { id: '1', label: '1', side: 'left', offset: 27, signal: 'passive', direction: 'passive', pinNumber: '1' },
      { id: '2', label: '2', side: 'right', offset: 27, signal: 'passive', direction: 'passive', pinNumber: '2' },
    ],
    defaultValue: '10k',
    kicadLibraryId: 'Device:R',
  },
  {
    kind: 'capacitor',
    category: 'passives',
    name: 'Capacitor',
    shortName: 'C',
    description: 'Non-polarized capacitor',
    modelStage: 'electrical',
    color: '#e5e1d8',
    size: { width: 78, height: 82 },
    ports: [
      { id: '1', label: '1', side: 'top', offset: 39, signal: 'passive', direction: 'passive', pinNumber: '1' },
      { id: '2', label: '2', side: 'bottom', offset: 39, signal: 'passive', direction: 'passive', pinNumber: '2' },
    ],
    defaultValue: '10n',
    kicadLibraryId: 'Device:C',
  },
  {
    kind: 'inductor',
    category: 'passives',
    name: 'Inductor',
    shortName: 'L',
    description: 'Two-terminal coil or choke',
    modelStage: 'electrical',
    color: '#e5e1d8',
    size: { width: 112, height: 54 },
    ports: [
      { id: '1', label: '1', side: 'left', offset: 27, signal: 'passive', direction: 'passive', pinNumber: '1' },
      { id: '2', label: '2', side: 'right', offset: 27, signal: 'passive', direction: 'passive', pinNumber: '2' },
    ],
    defaultValue: '10mH',
    kicadLibraryId: 'Device:L',
  },
  {
    kind: 'diode',
    category: 'passives',
    name: 'Signal diode',
    shortName: 'D',
    description: 'General-purpose silicon diode',
    modelStage: 'electrical',
    color: '#e5e1d8',
    size: { width: 96, height: 54 },
    ports: [
      { id: 'anode', label: 'A', side: 'left', offset: 27, signal: 'passive', direction: 'passive', pinNumber: '1' },
      { id: 'cathode', label: 'K', side: 'right', offset: 27, signal: 'passive', direction: 'passive', pinNumber: '2' },
    ],
    defaultValue: '1N4148',
    kicadLibraryId: 'Device:D',
  },
  {
    kind: 'led',
    category: 'passives',
    name: 'Light-emitting diode',
    shortName: 'LED',
    description: 'Indicator LED with selectable forward model',
    modelStage: 'electrical',
    color: '#ed8f68',
    size: { width: 100, height: 64 },
    ports: [
      { id: 'anode', label: 'A', side: 'left', offset: 38, signal: 'passive', direction: 'passive', pinNumber: '1' },
      { id: 'cathode', label: 'K', side: 'right', offset: 38, signal: 'passive', direction: 'passive', pinNumber: '2' },
    ],
    defaultValue: 'LED Red',
    kicadLibraryId: 'Device:LED',
  },
  {
    kind: 'zenerDiode',
    category: 'passives',
    name: 'Zener diode',
    shortName: 'ZD',
    description: 'Voltage clamp and reference diode',
    modelStage: 'electrical',
    color: '#8daadd',
    size: { width: 96, height: 54 },
    ports: [
      { id: 'anode', label: 'A', side: 'left', offset: 27, signal: 'passive', direction: 'passive', pinNumber: '1' },
      { id: 'cathode', label: 'K', side: 'right', offset: 27, signal: 'passive', direction: 'passive', pinNumber: '2' },
    ],
    defaultValue: '5V1',
    kicadLibraryId: 'Device:D_Zener',
  },
  {
    kind: 'potentiometer',
    category: 'passives',
    name: 'Potentiometer',
    shortName: 'POT',
    description: 'Panel or trim potentiometer',
    modelStage: 'electrical',
    color: '#e5e1d8',
    size: { width: 112, height: 72 },
    ports: [
      { id: '1', label: '1', side: 'left', offset: 35, signal: 'passive', direction: 'passive', pinNumber: '1' },
      { id: '2', label: '2', side: 'bottom', offset: 56, signal: 'passive', direction: 'passive', pinNumber: '2' },
      { id: '3', label: '3', side: 'right', offset: 35, signal: 'passive', direction: 'passive', pinNumber: '3' },
    ],
    defaultValue: '100k',
    kicadLibraryId: 'Device:R_Potentiometer',
  },
  {
    kind: 'switch',
    category: 'passives',
    name: 'SPST switch',
    shortName: 'SW',
    description: 'Toggle or momentary single-pole switch',
    modelStage: 'electrical',
    color: '#e5e1d8',
    size: { width: 112, height: 62 },
    ports: [
      { id: '1', label: '1', side: 'left', offset: 38, signal: 'passive', direction: 'passive', pinNumber: '1' },
      { id: '2', label: '2', side: 'right', offset: 38, signal: 'passive', direction: 'passive', pinNumber: '2' },
    ],
    defaultValue: 'SPST',
    defaultParameters: { closed: 0 },
    kicadLibraryId: 'Switch:SW_SPST',
  },
  {
    kind: 'npnBjt',
    category: 'passives',
    name: 'NPN transistor',
    shortName: 'NPN',
    description: 'General-purpose NPN bipolar transistor',
    modelStage: 'electrical',
    color: '#f2bf5e',
    size: { width: 112, height: 100 },
    ports: [
      { id: 'base', label: 'B', side: 'left', offset: 50, signal: 'passive', direction: 'passive', pinNumber: '2' },
      { id: 'collector', label: 'C', side: 'top', offset: 76, signal: 'passive', direction: 'passive', pinNumber: '1' },
      { id: 'emitter', label: 'E', side: 'bottom', offset: 76, signal: 'passive', direction: 'passive', pinNumber: '3' },
    ],
    defaultValue: '2N3904',
    kicadLibraryId: 'Transistor_BJT:Q_NPN_BCE',
  },
  {
    kind: 'pnpBjt',
    category: 'passives',
    name: 'PNP transistor',
    shortName: 'PNP',
    description: 'General-purpose PNP bipolar transistor',
    modelStage: 'electrical',
    color: '#f2bf5e',
    size: { width: 112, height: 100 },
    ports: [
      { id: 'base', label: 'B', side: 'left', offset: 50, signal: 'passive', direction: 'passive', pinNumber: '2' },
      { id: 'collector', label: 'C', side: 'bottom', offset: 76, signal: 'passive', direction: 'passive', pinNumber: '1' },
      { id: 'emitter', label: 'E', side: 'top', offset: 76, signal: 'passive', direction: 'passive', pinNumber: '3' },
    ],
    defaultValue: '2N3906',
    kicadLibraryId: 'Transistor_BJT:Q_PNP_BCE',
  },
  {
    kind: 'nMosfet',
    category: 'passives',
    name: 'N-channel MOSFET',
    shortName: 'NMOS',
    description: 'Enhancement-mode N-channel MOSFET',
    modelStage: 'electrical',
    color: '#68c7b2',
    size: { width: 112, height: 100 },
    ports: [
      { id: 'gate', label: 'G', side: 'left', offset: 50, signal: 'passive', direction: 'passive', pinNumber: '1' },
      { id: 'drain', label: 'D', side: 'top', offset: 76, signal: 'passive', direction: 'passive', pinNumber: '2' },
      { id: 'source', label: 'S', side: 'bottom', offset: 76, signal: 'passive', direction: 'passive', pinNumber: '3' },
    ],
    defaultValue: '2N7000',
    kicadLibraryId: 'Transistor_FET:Q_NMOS_GSD',
  },
  {
    kind: 'pMosfet',
    category: 'passives',
    name: 'P-channel MOSFET',
    shortName: 'PMOS',
    description: 'Enhancement-mode P-channel MOSFET',
    modelStage: 'electrical',
    color: '#68c7b2',
    size: { width: 112, height: 100 },
    ports: [
      { id: 'gate', label: 'G', side: 'left', offset: 50, signal: 'passive', direction: 'passive', pinNumber: '1' },
      { id: 'drain', label: 'D', side: 'bottom', offset: 76, signal: 'passive', direction: 'passive', pinNumber: '2' },
      { id: 'source', label: 'S', side: 'top', offset: 76, signal: 'passive', direction: 'passive', pinNumber: '3' },
    ],
    defaultValue: 'BSS84',
    kicadLibraryId: 'Transistor_FET:Q_PMOS_GSD',
  },
  {
    kind: 'ssi2131',
    category: 'ssi',
    name: 'SSI2131 VCO',
    shortName: '2131',
    description: 'Voltage-controlled oscillator · behavioral preview',
    modelStage: 'behavioral',
    color: '#f2bf5e',
    size: { width: 172, height: 154 },
    ports: [
      { id: 'pitch', label: 'V/OCT', side: 'left', offset: 43, signal: 'cv', direction: 'input', pinNumber: '6' },
      { id: 'pwm', label: 'PWM', side: 'left', offset: 82, signal: 'cv', direction: 'input', pinNumber: '3' },
      { id: 'sync', label: 'SYNC', side: 'left', offset: 121, signal: 'gate', direction: 'input', pinNumber: '10' },
      { id: 'saw', label: 'SAW', side: 'right', offset: 42, signal: 'audio', direction: 'output', pinNumber: '1' },
      { id: 'pulse', label: 'PULSE', side: 'right', offset: 80, signal: 'audio', direction: 'output', pinNumber: '2' },
      { id: 'tri', label: 'TRI', side: 'right', offset: 118, signal: 'audio', direction: 'output', pinNumber: '4' },
      { id: 'gnd', label: 'GND', side: 'bottom', offset: 86, signal: 'power', direction: 'powerInput', pinNumber: '9', defaultNet: 'GND' },
    ],
    defaultParameters: { coarse: 0, fine: 0, pulseWidth: 0.5 },
    kicadLibraryId: 'Saigen_SSI:SSI2131',
  },
  {
    kind: 'ssi2144',
    category: 'ssi',
    name: 'SSI2144 VCF',
    shortName: '2144',
    description: 'Four-pole low-pass filter · behavioral preview',
    modelStage: 'behavioral',
    color: '#68c7b2',
    size: { width: 172, height: 154 },
    ports: [
      { id: 'audio', label: 'AUDIO', side: 'left', offset: 42, signal: 'audio', direction: 'input', pinNumber: '1' },
      { id: 'cutoff', label: 'FC CV', side: 'left', offset: 80, signal: 'cv', direction: 'input', pinNumber: '15' },
      { id: 'resonance', label: 'RES CV', side: 'left', offset: 118, signal: 'cv', direction: 'input', pinNumber: '14' },
      { id: 'out', label: 'LP OUT', side: 'right', offset: 76, signal: 'audio', direction: 'output', pinNumber: '3' },
      { id: 'gnd', label: 'GND', side: 'bottom', offset: 86, signal: 'power', direction: 'powerInput', pinNumber: '9', defaultNet: 'GND' },
    ],
    defaultParameters: { cutoff: 1240, resonance: 0.42, drive: 3 },
    kicadLibraryId: 'Saigen_SSI:SSI2144',
  },
  {
    kind: 'ssi2164',
    category: 'ssi',
    name: 'SSI2164 VCA',
    shortName: '2164',
    description: 'Quad voltage-controlled amplifier · behavioral preview',
    modelStage: 'behavioral',
    color: '#ed8f68',
    size: { width: 172, height: 154 },
    ports: [
      { id: 'audio', label: 'AUDIO', side: 'left', offset: 44, signal: 'audio', direction: 'input', pinNumber: '2' },
      { id: 'cv', label: 'LEVEL CV', side: 'left', offset: 110, signal: 'cv', direction: 'input', pinNumber: '3' },
      { id: 'out', label: 'OUT', side: 'right', offset: 76, signal: 'audio', direction: 'output', pinNumber: '4' },
      { id: 'gnd', label: 'GND', side: 'bottom', offset: 86, signal: 'power', direction: 'powerInput', pinNumber: '8', defaultNet: 'GND' },
    ],
    defaultParameters: { level: 0.8 },
    kicadLibraryId: 'Saigen_SSI:SSI2164',
  },
  {
    kind: 'opAmp',
    category: 'utility',
    name: 'Op amp',
    shortName: 'OP',
    description: 'Ideal operational amplifier',
    modelStage: 'electrical',
    color: '#8daadd',
    size: { width: 126, height: 92 },
    ports: [
      { id: 'plus', label: '+', side: 'left', offset: 28, signal: 'passive', direction: 'input', pinNumber: '3' },
      { id: 'minus', label: '−', side: 'left', offset: 64, signal: 'passive', direction: 'input', pinNumber: '2' },
      { id: 'out', label: 'OUT', side: 'right', offset: 46, signal: 'passive', direction: 'output', pinNumber: '1' },
    ],
    kicadLibraryId: 'Amplifier_Operational:TL072',
  },
  {
    kind: 'comparator',
    category: 'utility',
    name: 'Comparator',
    shortName: 'COMP',
    description: 'Analog threshold comparator with gate output',
    modelStage: 'electrical',
    color: '#d7a3e8',
    size: { width: 126, height: 92 },
    ports: [
      { id: 'minus', label: '−', side: 'left', offset: 28, signal: 'passive', direction: 'input', pinNumber: '2' },
      { id: 'plus', label: '+', side: 'left', offset: 64, signal: 'passive', direction: 'input', pinNumber: '3' },
      { id: 'out', label: 'GATE', side: 'right', offset: 46, signal: 'gate', direction: 'output', pinNumber: '1' },
      { id: 'vPlus', label: 'V+', side: 'top', offset: 60, signal: 'power', direction: 'powerInput', pinNumber: '8' },
      { id: 'vMinus', label: 'V−', side: 'bottom', offset: 60, signal: 'power', direction: 'powerInput', pinNumber: '4' },
    ],
    defaultParameters: { threshold: 0, hysteresis: 0.05 },
    kicadLibraryId: 'Comparator:LM393',
  },
  {
    kind: 'envelope',
    category: 'utility',
    name: 'ADSR envelope',
    shortName: 'ADSR',
    description: 'Gate-driven contour generator',
    modelStage: 'behavioral',
    color: '#d7a3e8',
    size: { width: 126, height: 92 },
    ports: [
      { id: 'gate', label: 'GATE', side: 'left', offset: 46, signal: 'gate', direction: 'input', pinNumber: '1' },
      { id: 'out', label: 'CV OUT', side: 'right', offset: 46, signal: 'cv', direction: 'output', pinNumber: '2' },
    ],
    defaultParameters: { attack: 0.02, decay: 0.2, sustain: 0.7, release: 0.4 },
    kicadLibraryId: 'Saigen_Blocks:ADSR',
  },
  {
    kind: 'mixer',
    category: 'utility',
    name: 'Four-channel mixer',
    shortName: 'MIX',
    description: 'Summing mixer for audio signals',
    modelStage: 'behavioral',
    color: '#ed8f68',
    size: { width: 148, height: 132 },
    ports: [
      { id: 'in1', label: 'IN 1', side: 'left', offset: 25, signal: 'audio', direction: 'input', pinNumber: '1' },
      { id: 'in2', label: 'IN 2', side: 'left', offset: 52, signal: 'audio', direction: 'input', pinNumber: '2' },
      { id: 'in3', label: 'IN 3', side: 'left', offset: 79, signal: 'audio', direction: 'input', pinNumber: '3' },
      { id: 'in4', label: 'IN 4', side: 'left', offset: 106, signal: 'audio', direction: 'input', pinNumber: '4' },
      { id: 'out', label: 'SUM', side: 'right', offset: 66, signal: 'audio', direction: 'output', pinNumber: '5' },
    ],
    defaultParameters: { gain1: 0.25, gain2: 0.25, gain3: 0.25, gain4: 0.25 },
    kicadLibraryId: 'Saigen_Blocks:Mixer_4',
  },
  {
    kind: 'attenuverter',
    category: 'utility',
    name: 'Attenuverter',
    shortName: 'ATT±',
    description: 'Bipolar signal level and polarity control',
    modelStage: 'behavioral',
    color: '#9ad6c5',
    size: { width: 132, height: 84 },
    ports: [
      { id: 'in', label: 'IN', side: 'left', offset: 42, signal: 'passive', direction: 'input', pinNumber: '1' },
      { id: 'cv', label: 'CV', side: 'top', offset: 66, signal: 'cv', direction: 'input', pinNumber: '2' },
      { id: 'out', label: 'OUT', side: 'right', offset: 42, signal: 'passive', direction: 'output', pinNumber: '3' },
    ],
    defaultParameters: { gain: 1, offset: 0 },
    kicadLibraryId: 'Saigen_Blocks:Attenuverter',
  },
  {
    kind: 'audioOutput',
    category: 'utility',
    name: 'Audio output',
    shortName: 'OUT',
    description: 'Output jack and scope probe',
    modelStage: 'electrical',
    color: '#f2bf5e',
    size: { width: 96, height: 62 },
    ports: [{ id: 'in', label: 'IN', side: 'left', offset: 31, signal: 'audio', direction: 'input', pinNumber: '1' }],
    kicadLibraryId: 'Connector_Generic:Conn_01x01',
  },
  {
    kind: 'plus12V',
    category: 'utility',
    name: '+12 V rail',
    shortName: '+12V',
    description: 'Eurorack positive supply rail',
    modelStage: 'electrical',
    color: '#ed8f68',
    size: { width: 72, height: 54 },
    ports: [{ id: '1', label: '+12V', side: 'bottom', offset: 36, signal: 'power', direction: 'powerOutput', pinNumber: '1' }],
    defaultParameters: { voltage: 12 },
    kicadLibraryId: 'power:+12V',
  },
  {
    kind: 'minus12V',
    category: 'utility',
    name: '−12 V rail',
    shortName: '−12V',
    description: 'Eurorack negative supply rail',
    modelStage: 'electrical',
    color: '#8daadd',
    size: { width: 72, height: 54 },
    ports: [{ id: '1', label: '−12V', side: 'bottom', offset: 36, signal: 'power', direction: 'powerOutput', pinNumber: '1' }],
    defaultParameters: { voltage: -12 },
    kicadLibraryId: 'power:-12V',
  },
  {
    kind: 'ground',
    category: 'utility',
    name: 'Ground',
    shortName: 'GND',
    description: 'Circuit reference node',
    modelStage: 'electrical',
    color: '#a7acae',
    size: { width: 72, height: 62 },
    ports: [{ id: '1', label: 'GND', side: 'top', offset: 36, signal: 'power', direction: 'powerOutput', pinNumber: '1' }],
    kicadLibraryId: 'power:GND',
  },
  {
    kind: 'probe',
    category: 'utility',
    name: 'Scope probe',
    shortName: 'PROBE',
    description: 'Observe a net in the scope',
    modelStage: 'visual',
    color: '#8daadd',
    size: { width: 86, height: 58 },
    ports: [{ id: 'in', label: 'IN', side: 'left', offset: 29, signal: 'passive', direction: 'passive', pinNumber: '1' }],
    kicadLibraryId: 'Connector:TestPoint',
  },
  {
    kind: 'unknown',
    category: 'utility',
    name: 'Unsupported symbol',
    shortName: '?',
    description: 'Preserved KiCad symbol without a simulation model',
    modelStage: 'visual',
    color: '#a7acae',
    size: { width: 132, height: 92 },
    ports: [],
    kicadLibraryId: 'Saigen:Unsupported',
  },
]

export const catalogByKind = Object.fromEntries(
  componentCatalog.map((component) => [component.kind, component]),
) as Record<ComponentKind, CatalogComponent>

export const categoryLabels = {
  sources: 'Sources',
  passives: 'Passives',
  ssi: 'Sound Semiconductor',
  utility: 'Utility',
} as const

export const referencePrefix: Record<ComponentKind, string> = {
  audioInput: 'V',
  cvInput: 'J',
  gateInput: 'J',
  triggerSource: 'V',
  functionGenerator: 'V',
  resistor: 'R',
  capacitor: 'C',
  inductor: 'L',
  diode: 'D',
  led: 'D',
  zenerDiode: 'D',
  potentiometer: 'RV',
  switch: 'SW',
  npnBjt: 'Q',
  pnpBjt: 'Q',
  nMosfet: 'Q',
  pMosfet: 'Q',
  opAmp: 'U',
  comparator: 'U',
  ssi2131: 'U',
  ssi2144: 'U',
  ssi2164: 'U',
  envelope: 'U',
  lfo: 'U',
  noiseSource: 'U',
  clock: 'U',
  mixer: 'U',
  attenuverter: 'U',
  audioOutput: 'J',
  plus12V: '#PWR',
  minus12V: '#PWR',
  ground: '#PWR',
  probe: 'TP',
  unknown: 'U',
}
