import type { CircuitDocument, SimulationControls } from './types'

export const demoCircuit: CircuitDocument = {
  schemaVersion: 1,
  id: 'ssi-voice-demo',
  title: 'SSI signal path / voice 01',
  description: 'A voltage-controlled oscillator, four-pole filter, and exponential VCA voice.',
  revision: 7,
  components: [
    {
      id: 'pitch-cv',
      kind: 'cvInput',
      reference: 'J1',
      label: '1V/OCT',
      position: { x: 38, y: 116 },
      parameters: { voltage: 0 },
    },
    {
      id: 'gate',
      kind: 'gateInput',
      reference: 'J2',
      label: 'GATE',
      position: { x: 38, y: 405 },
      parameters: { voltage: 5, state: 1 },
    },
    {
      id: 'vco',
      kind: 'ssi2131',
      reference: 'U1',
      label: 'VCO CORE',
      position: { x: 186, y: 92 },
      parameters: { coarse: 0, fine: 0, pulseWidth: 0.5 },
    },
    {
      id: 'vcf',
      kind: 'ssi2144',
      reference: 'U2',
      label: '4-POLE VCF',
      position: { x: 442, y: 92 },
      parameters: { cutoff: 1240, resonance: 0.42, drive: 3 },
    },
    {
      id: 'vca',
      kind: 'ssi2164',
      reference: 'U3',
      label: 'FINAL VCA',
      position: { x: 698, y: 92 },
      parameters: { level: 0.78 },
    },
    {
      id: 'audio-out',
      kind: 'audioOutput',
      reference: 'J3',
      label: 'MAIN OUT',
      position: { x: 954, y: 138 },
      parameters: {},
    },
    {
      id: 'envelope',
      kind: 'envelope',
      reference: 'U4',
      label: 'AMP ENV',
      position: { x: 526, y: 390 },
      parameters: { attack: 0.02, decay: 0.2, sustain: 0.7, release: 0.4 },
    },
    {
      id: 'ground',
      kind: 'ground',
      reference: '#PWR01',
      label: '0V',
      position: { x: 795, y: 446 },
      parameters: {},
    },
  ],
  connections: [
    {
      id: 'pitch-to-vco',
      from: { componentId: 'pitch-cv', portId: 'out' },
      to: { componentId: 'vco', portId: 'pitch' },
      signal: 'cv',
    },
    {
      id: 'vco-to-vcf',
      from: { componentId: 'vco', portId: 'saw' },
      to: { componentId: 'vcf', portId: 'audio' },
      signal: 'audio',
    },
    {
      id: 'vcf-to-vca',
      from: { componentId: 'vcf', portId: 'out' },
      to: { componentId: 'vca', portId: 'audio' },
      signal: 'audio',
    },
    {
      id: 'vca-to-out',
      from: { componentId: 'vca', portId: 'out' },
      to: { componentId: 'audio-out', portId: 'in' },
      signal: 'audio',
    },
    {
      id: 'gate-to-envelope',
      from: { componentId: 'gate', portId: 'out' },
      to: { componentId: 'envelope', portId: 'gate' },
      signal: 'gate',
    },
    {
      id: 'envelope-to-vca',
      from: { componentId: 'envelope', portId: 'out' },
      to: { componentId: 'vca', portId: 'cv' },
      signal: 'cv',
    },
    {
      id: 'ground-to-vca',
      from: { componentId: 'ground', portId: '1' },
      to: { componentId: 'vca', portId: 'gnd' },
      signal: 'power',
    },
  ],
}

export const defaultControls: SimulationControls = {
  running: true,
  monitor: false,
  note: 48,
  cutoff: 1240,
  resonance: 0.42,
  drive: 3,
  envelope: 0.78,
}
