import type { CircuitDocument, SimulationControls } from './types'

export const demoCircuit: CircuitDocument = {
  schemaVersion: 1,
  id: 'ssi-voice-demo',
  title: 'SSI signal path / voice 01',
  description: 'A voltage-controlled oscillator, four-pole filter, and exponential VCA voice.',
  revision: 8,
  components: [
    {
      id: 'pitch-cv',
      kind: 'cvInput',
      reference: 'J1',
      label: '1V/OCT',
      position: { x: 38, y: 121 },
      parameters: { voltage: 0 },
    },
    {
      id: 'gate',
      kind: 'gateInput',
      reference: 'J2',
      label: 'GATE',
      position: { x: 38, y: 600 },
      parameters: { voltage: 5, state: 1 },
    },
    {
      id: 'vco',
      kind: 'ssi2131',
      reference: 'U1',
      label: 'VCO CORE',
      position: { x: 210, y: 102 },
      parameters: { coarse: 0, fine: 0, pulseWidth: 0.5 },
    },
    {
      id: 'vcf',
      kind: 'ssi2144',
      reference: 'U2',
      label: '4-POLE VCF',
      position: { x: 560, y: 104 },
      parameters: { cutoff: 1240, resonance: 0.42, drive: 3 },
    },
    {
      id: 'vca',
      kind: 'ssi2164',
      reference: 'U3',
      label: 'FINAL VCA',
      position: { x: 910, y: 80 },
      parameters: { level: 0.78 },
    },
    {
      id: 'audio-out',
      kind: 'audioOutput',
      reference: 'J3',
      label: 'MAIN OUT',
      position: { x: 1280, y: 133 },
      parameters: {},
    },
    {
      id: 'envelope',
      kind: 'envelope',
      reference: 'U4',
      label: 'AMP ENV',
      position: { x: 610, y: 570 },
      parameters: { attack: 0.02, decay: 0.2, sustain: 0.7, release: 0.4 },
    },
    {
      id: 'plus5',
      kind: 'plus5V',
      reference: '#PWR02',
      label: '+5V',
      position: { x: 180, y: 500 },
      parameters: { voltage: 5 },
    },
    {
      id: 'vref',
      kind: 'vref2V5',
      reference: '#PWR03',
      label: '2V5 REF',
      position: { x: 290, y: 500 },
      parameters: { voltage: 2.5 },
    },
    {
      id: 'plus12',
      kind: 'plus12V',
      reference: '#PWR04',
      label: '+12V',
      position: { x: 410, y: 500 },
      parameters: { voltage: 12 },
    },
    {
      id: 'minus12',
      kind: 'minus12V',
      reference: '#PWR05',
      label: '−12V',
      position: { x: 510, y: 500 },
      parameters: { voltage: -12 },
    },
    {
      id: 'ground',
      kind: 'ground',
      reference: '#PWR01',
      label: '0V',
      position: { x: 1045, y: 570 },
      parameters: {},
    },
  ],
  connections: [
    {
      id: 'pitch-to-vco',
      from: { componentId: 'pitch-cv', portId: 'out' },
      to: { componentId: 'vco', portId: 'pitch' },
      signal: 'cv',
    },
    {
      id: 'vco-to-vcf',
      from: { componentId: 'vco', portId: 'saw' },
      to: { componentId: 'vcf', portId: 'audio' },
      signal: 'audio',
    },
    {
      id: 'vcf-to-vca',
      from: { componentId: 'vcf', portId: 'out' },
      to: { componentId: 'vca', portId: 'audio' },
      signal: 'audio',
    },
    {
      id: 'vca-to-out',
      from: { componentId: 'vca', portId: 'out' },
      to: { componentId: 'audio-out', portId: 'in' },
      signal: 'audio',
    },
    {
      id: 'gate-to-envelope',
      from: { componentId: 'gate', portId: 'out' },
      to: { componentId: 'envelope', portId: 'gate' },
      signal: 'gate',
    },
    {
      id: 'envelope-to-vca',
      from: { componentId: 'envelope', portId: 'out' },
      to: { componentId: 'vca', portId: 'cv' },
      signal: 'cv',
    },
    {
      id: 'plus5-to-vco',
      from: { componentId: 'plus5', portId: '1' },
      to: { componentId: 'vco', portId: 'vPlus' },
      signal: 'power',
    },
    {
      id: 'vref-to-vco',
      from: { componentId: 'vref', portId: '1' },
      to: { componentId: 'vco', portId: 'vref' },
      signal: 'power',
    },
    {
      id: 'plus12-to-vcf',
      from: { componentId: 'plus12', portId: '1' },
      to: { componentId: 'vcf', portId: 'vPlus' },
      signal: 'power',
    },
    {
      id: 'plus12-to-vca',
      from: { componentId: 'plus12', portId: '1' },
      to: { componentId: 'vca', portId: 'vPlus' },
      signal: 'power',
    },
    {
      id: 'minus12-to-vco',
      from: { componentId: 'minus12', portId: '1' },
      to: { componentId: 'vco', portId: 'vMinus' },
      signal: 'power',
    },
    {
      id: 'minus12-to-vcf',
      from: { componentId: 'minus12', portId: '1' },
      to: { componentId: 'vcf', portId: 'vMinus' },
      signal: 'power',
    },
    {
      id: 'minus12-to-vca',
      from: { componentId: 'minus12', portId: '1' },
      to: { componentId: 'vca', portId: 'vMinus' },
      signal: 'power',
    },
    {
      id: 'ground-to-vca',
      from: { componentId: 'ground', portId: '1' },
      to: { componentId: 'vca', portId: 'gnd' },
      signal: 'power',
    },
  ],
}

export const defaultControls: SimulationControls = {
  running: true,
  monitor: false,
  note: 48,
  cutoff: 1240,
  resonance: 0.42,
  drive: 3,
  envelope: 0.78,
}
